# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69c29816b2b80b06d173af95c401f26b12504e588bdcd805507e7113b9696526273cb9cf3b35b8d65a59795ddd2ec0429562d52a4514d6eae2d198b248537421

test:
  secret_key_base: c30ccac42b7e6f45954534123b663499df5ea593dc93e116706029b80442f7776538877636cc484b3fb8d4989093f50679afafd00ec898ab2352d30d5aece747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
